apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
      a3ViZUNBMB4XDTI1MTExNzE2MDY0NFoXDTM1MTExNjE2MDY0NFowFTETMBEGA1UE
      AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANnS
      X6dQe4JyevmWQ2JM4OPdrnSLp2N3Br3iENtajnIVDBCcOQtHuFmpyips8nOTpQ6l
      yVWNPyToIT8Nmgpu8+1R4wNMGIZVm3aDLNC7f2FH3A7d13zTclPywh2cfHJGqkfY
      VnwmyMGWbhb4D+lBto6Cj98DcA+ozXr50IATGW/jcKioMiNaoGYdrB2lrs/U1Ku5
      vbH2Vln5nBcNE3ndegjrTtVZBSbYtKosJwcYmdm+mousCYJ9JPjuurQdVQEyeCeR
      3B86wP5PQ8vzR9zIihRMgnIboLyaS1lcvVCcAuAHAx5Xi9v7U9UTnd6+vg0wAWX1
      gMCij+vgKiWi2UsSOcUCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
      MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
      BBTCTaMoDyrPb8XoCGg3pLrLGQ/vxTANBgkqhkiG9w0BAQsFAAOCAQEA2YONIFo2
      5UUwF3n0MJiveSkIqa6FrB2Ddo2aZrODmkcBYNbq/iuprwtN25vbqFBDWHHz1zRJ
      ObcwiCRl8pdmE7Qk3GNpHeJ6eDejjG6a8PEyMCMYMzpEAufx8cTSskt0b0Wmu5cm
      QF7oldqk1rrUgNSKTpi49erav4wman2k5sHKv51IYlXykf/smrEr9VkhNL7cNDUO
      cpXp9d+wQ3EJpZ6ye9c+BOaJibpfiXMN0KzCjB90/hcEaMgD88+EVdLAzWeYk5xT
      r/IME5reHxMlkUvK+Z83gFbJpJUiAB5MKvatqHJTZ3Hi9pJIHpYiX019Dmmwsv6H
      mpZpWxvvapx2Lw==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2025-11-18T17:59:19Z"
    name: kube-root-ca.crt
    namespace: webapp
    resourceVersion: "4701"
    uid: b5b89b36-e188-4a72-b15e-40fe0ea62276
kind: List
metadata:
  resourceVersion: ""
