apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lighttpdcgi
  namespace: webapp
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  tls:
    - secretName: le-cert
      hosts:
        - yeah.example.com
  rules:
    - host: yeah.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lighttpdcgi
                port:
                  number: 80
