apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: IngressClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"IngressClass","metadata":{"annotations":{},"name":"traefik"},"spec":{"controller":"traefik.io/ingress-controller"}}
    creationTimestamp: "2025-11-18T19:49:31Z"
    generation: 1
    name: traefik
    resourceVersion: "11127"
    uid: 655123e5-dec6-4150-905e-bc9a2fbd3d3f
  spec:
    controller: traefik.io/ingress-controller
kind: List
metadata:
  resourceVersion: ""
