apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"traefik.io/ingress.class":"traefik","traefik.io/router.entrypoints":"websecure"},"name":"lighttpdcgi","namespace":"webapp"},"spec":{"ingressClassName":"traefik","rules":[{"host":"yeah.webterrorist.net","http":{"paths":[{"backend":{"service":{"name":"lighttpdcgi","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{"hosts":["yeah.webterrorist.net"],"secretName":"webapp-tls"}]}}
      traefik.io/ingress.class: traefik
      traefik.io/router.entrypoints: websecure
    creationTimestamp: "2025-11-18T18:03:00Z"
    generation: 2
    name: lighttpdcgi
    namespace: webapp
    resourceVersion: "16898"
    uid: 9b5f06a6-71cd-4a5f-bb4b-9e3a96cd04d4
  spec:
    ingressClassName: traefik
    rules:
    - host: yeah.webterrorist.net
      http:
        paths:
        - backend:
            service:
              name: lighttpdcgi
              port:
                number: 80
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - yeah.webterrorist.net
      secretName: webapp-tls
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
