apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"lighttpdcgi","namespace":"webapp"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"lighttpdcgi"},"type":"ClusterIP"}}
    creationTimestamp: "2025-11-18T18:17:07Z"
    name: lighttpdcgi
    namespace: webapp
    resourceVersion: "5800"
    uid: de32c19f-a90e-44fa-b217-9f7601f477ea
  spec:
    clusterIP: 10.96.131.108
    clusterIPs:
    - 10.96.131.108
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: lighttpdcgi
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"traefik","namespace":"webapp"},"spec":{"ports":[{"name":"web","nodePort":30080,"port":80},{"name":"websecure","nodePort":30443,"port":443}],"selector":{"app":"traefik"},"type":"NodePort"}}
    creationTimestamp: "2025-11-18T18:02:54Z"
    name: traefik
    namespace: webapp
    resourceVersion: "17621"
    uid: 2bc59153-4ebf-4d15-95fe-e9a04c3c336e
  spec:
    clusterIP: 10.111.46.54
    clusterIPs:
    - 10.111.46.54
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: web
      nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 80
    - name: websecure
      nodePort: 30443
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      app: traefik
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
